# l10n.yaml配置

# 告诉 Flutter 工具，你的语言文件 (.arb) 存放在哪里。
arb-dir: lib/l10n

# 告诉 Flutter 工具，哪个是你的“模板”语言文件，通常是英文。
template-arb-file: app_en.arb

# 告诉 Flutter 工具，生成的 Dart 文件应该叫什么名字。
output-localization-file: app_localizations.dart

# 告诉 Flutter 工具，生成的 Dart 类的名字应该叫什么。
output-class: AppLocalizations

# 告诉 Flutter 工具，生成的 Dart 文件应该放在哪个目录下。
output-dir: lib/generated

# 生成未翻译词条报告文件（当运行 flutter gen-l10n 时自动输出未翻译的 key 列表）
untranslated-messages-file: lib/l10n/untranslated.json

# 确保生成的 getter 不是可空的，与旧版本行为保持一致。
nullable-getter: false
