import 'dart:async';
import 'dart:io';
import 'package:build/build.dart';

class LiveActivitySetupBuilder implements Builder {
  final BuilderOptions options;

  LiveActivitySetupBuilder(this.options);

  @override
  Map<String, List<String>> get buildExtensions => {
        r'$lib$': ['ios_live_activity_setup.info'],
      };

  @override
  Future<void> build(BuildStep buildStep) async {
    try {
      final iosDir = Directory('ios');
      final xcodeProj = Directory('ios/Runner.xcodeproj');

      // 仅在存在 ios 目录且运行在具备 setup 环境时自动执行同步检查
      if (iosDir.existsSync() && xcodeProj.existsSync()) {
        if (Platform.isMacOS) {
          final result = await Process.run('dart', [
            'run',
            'live_activity_kit:setup',
          ]);
          final outputId = AssetId(
            buildStep.inputId.package,
            'lib/ios_live_activity_setup.info',
          );
          await buildStep.writeAsString(
            outputId,
            '// Auto-generated by live_activity_setup_generator\n'
            '// ExitCode: ${result.exitCode}\n'
            '// Last sync: ${DateTime.now().toIso8601String()}\n',
          );
        } else {
          final outputId = AssetId(
            buildStep.inputId.package,
            'lib/ios_live_activity_setup.info',
          );
          await buildStep.writeAsString(
            outputId,
            '// Auto-generated: Non-macOS environment (skipped setup execution).\n',
          );
        }
      }
    } catch (_) {
      // 忽略构建期外部命令异常，保证主构建流程平稳
    }
  }
}
