
/// 预定义标签列表
/// 用于初始化系统中的标准标签
const List<Map<String, dynamic>> predefinedLabels = [
  {'text': 'Fraud Scam Likely', 'icon': 'fraud_icon'},
  {'text': 'Spam Likely', 'icon': 'spam_icon'},
  {'text': 'Telemarketing', 'icon': 'telemarketing_icon'},
  {'text': 'Robocall', 'icon': 'robot_icon'},
  {'text': 'Delivery', 'icon': 'delivery_icon'},
  {'text': 'Takeaway', 'icon': 'food_icon'},
  {'text': 'Ridesharing', 'icon': 'car_icon'},
  {'text': 'Insurance', 'icon': 'insurance_icon'},
  {'text': 'Loan', 'icon': 'loan_icon'},
  {'text': 'Customer Service', 'icon': 'service_icon'},
  {'text': 'Unknown', 'icon': 'question_icon'},
  {'text': 'Financial', 'icon': 'finance_icon'},
  {'text': 'Bank', 'icon': 'bank_icon'},
  {'text': 'Education', 'icon': 'education_icon'},
  {'text': 'Medical', 'icon': 'medical_icon'},
  {'text': 'Charity', 'icon': 'charity_icon'},
  {'text': 'Other', 'icon': 'other_icon'},
  {'text': 'Debt Collection', 'icon': 'debt_icon'},
  {'text': 'Survey', 'icon': 'survey_icon'},
  {'text': 'Political', 'icon': 'political_icon'},
  {'text': 'Ecommerce', 'icon': 'shopping_icon'},
  {'text': 'Risk', 'icon': 'risk_icon'},
  {'text': 'Agent', 'icon': 'agent_icon'},
  {'text': 'Recruiter', 'icon': 'recruiter_icon'},
  {'text': 'Headhunter', 'icon': 'headhunter_icon'},  
  {'text': 'Silent Call(Voice Clone)', 'icon': 'silent_call_icon'}, 
];
