allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

subprojects {

    plugins.withId('com.android.library') {
        androidComponents {
            finalizeDsl { extension ->
                extension.compileSdk = 37
            }
        }
    }

    tasks.withType(JavaCompile).configureEach {
        sourceCompatibility = "17"
        targetCompatibility = "17"
    }

    tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
        kotlinOptions {
            jvmTarget = "17"
        }
    }

    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.layout.buildDirectory
}
