builders:
  label_generator:
    import: "package:label_generator/builder.dart"
    builder_factories: ["labelBuilder"]
    build_extensions: {".dart": [".label_gen.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen:combining_builder"]
