// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAynopBYtSMQhy2woddAHdckEHYxY5gM20',
    appId: '1:213507864895:web:c21964005e8f5dc9013b8a',
    messagingSenderId: '213507864895',
    projectId: 'yourcallyourrule-b2bfa',
    authDomain: 'yourcallyourrule-b2bfa.firebaseapp.com',
    storageBucket: 'yourcallyourrule-b2bfa.firebasestorage.app',
    measurementId: 'G-VBKGZE2XYH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0HQiX40ERefoU_bOQexkNn7VL20x9UZI',
    appId: '1:213507864895:android:24b52b0d9f8cf30f013b8a',
    messagingSenderId: '213507864895',
    projectId: 'yourcallyourrule-b2bfa',
    storageBucket: 'yourcallyourrule-b2bfa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZNHcX0cuGIf938-M-6AhyJD36Lu1X0t4',
    appId: '1:213507864895:ios:0e943e303b8e9822013b8a',
    messagingSenderId: '213507864895',
    projectId: 'yourcallyourrule-b2bfa',
    storageBucket: 'yourcallyourrule-b2bfa.firebasestorage.app',
    iosBundleId: 'com.yours.yourcallyourrule',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZNHcX0cuGIf938-M-6AhyJD36Lu1X0t4',
    appId: '1:213507864895:ios:0e943e303b8e9822013b8a',
    messagingSenderId: '213507864895',
    projectId: 'yourcallyourrule-b2bfa',
    storageBucket: 'yourcallyourrule-b2bfa.firebasestorage.app',
    iosBundleId: 'com.yours.yourcallyourrule',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAynopBYtSMQhy2woddAHdckEHYxY5gM20',
    appId: '1:213507864895:web:f16c57d94dd2cafb013b8a',
    messagingSenderId: '213507864895',
    projectId: 'yourcallyourrule-b2bfa',
    authDomain: 'yourcallyourrule-b2bfa.firebaseapp.com',
    storageBucket: 'yourcallyourrule-b2bfa.firebasestorage.app',
    measurementId: 'G-G3M4JD4FLB',
  );
}
