
const List<Map<String, dynamic>> predefinedLabels = [
  {'label': 'Fraud Scam Likely'},
  {'label': 'Spam Likely'},
  {'label': 'Telemarketing'},
  {'label': 'Robocall'},
  {'label': 'Delivery'},
  {'label': 'Takeaway'},
  {'label': 'Ridesharing'},
  {'label': 'Insurance'},
  {'label': 'Loan'},
  {'label': 'Customer Service'},
  {'label': 'Unknown'},
  {'label': 'Financial'},
  {'label': 'Bank'},
  {'label': 'Education'},
  {'label': 'Medical'},
  {'label': 'Charity'},
  {'label': 'Other'},
  {'label': 'Debt Collection'},
  {'label': 'Survey'},
  {'label': 'Political'},
  {'label': 'Ecommerce'},
  {'label': 'Risk'},
  {'label': 'Agent'},
  {'label': 'Recruiter'},
  {'label': 'Headhunter'},  
  {'label': 'Silent Call(Voice Clone?)'}, 
];
