#====================================================================================
#== Flutter & Android Core Rules (ABSOLUTELY NECESSARY)
#====================================================================================

# Flutter's default rules to protect the engine and its plugins.
# Do not remove these.
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.embedding.**  { *; }
-dontwarn io.flutter.embedding.**

# This rule is CRITICAL for preventing UnsatisfiedLinkError.
# It tells ProGuard to not rename any native (JNI) methods and their containing classes.
-keepclasseswithmembernames class * {
    native <methods>;
}

# Keep common Android components from being stripped away.
-keep public class * extends android.app.Activity
-keep public class * extends android.app.Application
-keep public class * extends android.app.Service
-keep public class * extends android.content.BroadcastReceiver
-keep public class * extends android.content.ContentProvider
-keep public class * extends android.view.View

# Keep Parcelable classes and their CREATOR field, essential for data transfer.
-keepnames class * implements android.os.Parcelable
-keepclassmembers class * implements android.os.Parcelable {
  public static final android.os.Parcelable$Creator CREATOR;
}

#====================================================================================
#== Firebase & Google Services Rules
#====================================================================================

# General rules for Firebase SDKs and Google Play Services.
-keep class com.google.firebase.** { *; }
-keep public class com.google.android.gms.** { *; }
-dontwarn com.google.android.gms.**

# Specific keep rules required by Firebase libraries.
-keepattributes Signature, *Annotation*
-keepnames class com.google.android.gms.measurement.AppMeasurement
-keep class com.google.firebase.messaging.** { *; }

# For Firestore or other libraries that use gRPC.
-keepclassmembers class * extends io.grpc.internal.Generateddh {
  <init>(...);
}

# For libraries using Chromium's network stack.
-keep class org.chromium.net.** { *; }

#====================================================================================
#== Google Mobile Ads (AdMob) Rules
#====================================================================================
# Required if you use the google_mobile_ads plugin.
-keep public class com.google.android.gms.ads.** {
   public *;
}
-keep class com.google.ads.mediation.** { *; }

#====================================================================================
#== AndroidX & Common Jetpack Library Rules
#====================================================================================

# For AndroidX WorkManager (detected from your logs).
-keep class androidx.work.** { *; }
-dontwarn androidx.work.**

# For AndroidX WindowManager extensions (from your original rules).
-keep class androidx.window.extensions.** { *; }
-keep class androidx.window.sidecar.** { *; }
-keep interface androidx.window.extensions.** { *; }
-keep interface androidx.window.sidecar.** { *; }
-dontwarn androidx.window.extensions.**
-dontwarn androidx.window.sidecar.**

#====================================================================================
#== Other Third-Party Library Rules (Add as needed)
#====================================================================================

# BouncyCastle cryptography library (from your original rules).
-dontwarn org.bouncycastle.**

# Rules for libraries that might use Gson for JSON serialization.
-keep class com.google.gson.stream.** { *; }
-keep class * implements com.google.gson.TypeAdapterFactory
-keep class * implements com.google.gson.JsonSerializer
-keep class * implements com.google.gson.JsonDeserializer

# For Microsoft MSAL library (if used, as indicated by BrowserTabActivity in some projects).
-keep class com.microsoft.identity.client.** { *; }
-dontwarn com.microsoft.identity.client.**

#====================================================================================
#== Suppress Warnings (Generated by AGP)
#====================================================================================
# These are safe warnings to ignore, typically related to optional dependencies.
# This section consolidates all the -dontwarn rules from your original file.
-dontwarn edu.umd.cs.findbugs.annotations.**