name: dart Cached Flutter Build, Sign and Release

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: platform-tools build-tools;34.0.0
          
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
          cache: true
          cache-key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}

      - run: flutter pub get
      
      # Cache Gradle dependencies
      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Flutter Doctor
        run: flutter doctor -v


      # Decode and place keystore
      - name: Decode keystore
        run: echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > android/app/key.jks

      # Create key.properties file
      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.ANDROID_KEYSTORE_ALIAS }}" >> android/key.properties
          echo "storeFile=key.jks" >> android/key.properties

      # Build and Sign AAB and APKs using Flutter's built-in signing
      - name: Build and Sign AAB and APKs
        run: |
          flutter build appbundle -v 
          flutter build apk --split-per-abi

      # Cache Flutter build files
      - name: Cache Flutter Build Files
        uses: actions/cache@v3
        with:
          path: |
            build
            .dart_tool
          key: ${{ runner.os }}-flutter-build-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-build-

      # Upload signed AAB and APKs as artifacts
      - name: Upload Signed Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: signed-release-artifacts
          path: |
            build/app/outputs/bundle/release/app-release.aab
            build/app/outputs/apk/release/*.apk

      - name: Extract pubspec version
        run: |
          echo "PUBSPEC_VERSION=$(grep -oP 'version:\s*\K[^+]+(?=\+)' pubspec.yaml)" >> $GITHUB_ENV

      - name: Upload Release 
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.MY_PAT }}
          tag: v${{ env.PUBSPEC_VERSION }} 
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          allowUpdates: true
          artifacts: |
            signed-release-artifacts/*
            build/app/outputs/bundle/release/app-release.aab
            build/app/outputs/apk/release/*.apk