name: 运行Flutter Debug Build
on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build Type (aab/apk/both)'
        required: true
        default: 'both'

        
jobs:
  debug-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
          
      - name: Install Dependencies
        run: flutter pub get
          
      - name: Decode Keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > android/app/key.jks
          
      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.ANDROID_KEYSTORE_ALIAS }}" >> android/key.properties
          echo "storeFile=key.jks" >> android/key.properties
          
      - name: Build Release
        run: |
          if [[ "${{ github.event.inputs.build_type }}" == "aab" || "${{ github.event.inputs.build_type }}" == "both" ]]; then
            flutter build appbundle --verbose
          fi
          if [[ "${{ github.event.inputs.build_type }}" == "apk" || "${{ github.event.inputs.build_type }}" == "both" ]]; then
            flutter build apk --split-per-abi --verbose
          fi
          
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-build-artifacts
          path: |
            build/app/outputs/bundle/release/app-release.aab
            build/app/outputs/apk/release/*.apk
            
      - name: Extract Version
        run: |
          echo "PUBSPEC_VERSION=$(grep -oP 'version:\s*\K[^+]+(?=\+)' pubspec.yaml)" >> $GITHUB_ENV