name: chat 测试 tt

on:
  workflow_dispatch:
  #push:
  #  branches:
   #   - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout 代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 设置 Flutter 环境
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'  # 使用合适的 Flutter 版本

      # 3. 解密 Keystore 文件
      - name: Decode Keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > android/app/key.jks

      # 4. 创建 key.properties 文件
      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.ANDROID_KEYSTORE_ALIAS }}" >> android/key.properties
          echo "storeFile=key.jks" >> android/key.properties

      # 5. 安装 Flutter 依赖
      - name: Install dependencies
        run: flutter pub get

      # 6. 编译 Flutter AAB 文件
      - name: Build AAB
        run: flutter build appbundle --release

      # 7. 上传构建的 AAB 文件作为 artifact
      - name: Upload AAB artifact
        uses: actions/upload-artifact@v3
        with:
          name: flutter-aab
          path: build/app/outputs/bundle/release/app-release.aab
