name: chat 测试 tt

on:
  workflow_dispatch:
  #push:
  #  branches:
   #   - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout 代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 设置 Java 17
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17.x'


      # 4. 解密 Keystore 文件
      - name: Decode Keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > android/app/key.jks

      # 5. 创建 key.properties 文件
      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.ANDROID_KEYSTORE_ALIAS }}" >> android/key.properties
          echo "storeFile=key.jks" >> android/key.properties



      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.0
      - run: flutter pub get
      

      - run: flutter build appbundle -v

      # 8. 上传构建的 AAB 文件作为 artifact
      - name: Upload AAB artifact
        uses: actions/upload-artifact@v3
        with:
          name: flutter-aab
          path: build/app/outputs/bundle/release/app-release.aab
